  name: build

  on: 
    push: 
      branches: ["main"]
    
  jobs:
    build_and_deploy:
      name: build-app
      runs-on: ubuntu-latest

      strategy:
        matrix:
          os: [ubuntu-latest]
          node-version: [20.x]

      concurrency: ci-${{github.ref}}

      steps:
        - uses: actions/checkout@v3
        
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v2
          with:
              node-version: ${{ matrix.node-version }}

        - name: Install Deps
          run: npm install

        - name: Build
          run: npm run build
        
        - name: Deploy
          uses: JamesIves/github-pages-deploy-action@v4
          with:
            folder: ./app/dist
            branch: release/dist
