name: build

on:
  push:
    branches: ["main"]
  workflow_dispatch:

concurrency: ci-${{ github.ref }}

jobs:
  build_and_deploy:
    name: build-app
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3

      - name: Install Deps
        run: bun install

      - name: Build
        run: bun run build

      - name: Deploy to release/dist
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./dist
          branch: release/dist
