  name: build

  on: 
    push: 
      branches: ["main"]
    
  jobs:
    build_and_deploy:
      name: build-app
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        
        - uses: oven-sh/setup-bun@v1
        
        - name: Install dependencies and build
          run: |
            cd ./app
            bun install
            bun run build
        
        - name: Deploy
          uses: JamesIves/github-pages-deploy-action@v4
          with:
            folder: ./app/dist
            branch: pre-release/dist
